/* 
 * Copyright (C) 2017 Edward F Sowell
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JCNAConcours;

import static JCNAConcours.AddConcoursEntryDialog.okDialog;
//import static JCNAConcours.ConcoursGUI.theConcours;
import java.awt.Component;
import java.awt.Dimension;
//import java.awt.event.ItemEvent;
//import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.util.logging.Logger;
import javax.swing.BoxLayout;
//import javax.swing.Icon;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import us.efsowell.concours.lib.Concours;
import us.efsowell.concours.lib.ConcoursClass;
//import us.efsowell.concours.lib.ConcoursPersonnel;
//import us.efsowell.concours.lib.JCNAClass;
import us.efsowell.concours.lib.Judge;
import us.efsowell.concours.lib.Judges;
import us.efsowell.concours.lib.LoadSQLiteConcoursDatabase;

/**
 *
 * @author Ed Sowell
 */
public class AddCustomJudgeTeamDialog extends javax.swing.JDialog {
    //JPanel pnlJCNAClassGroups;
    JPanel pnlJudges;
    JScrollPane scrollPaneJudges;
    
    Judge[] judgeArray;
    Concours theConcours;
    //ConcoursPersonnel theConcoursePersonnel;
    Judges theConcoursJudges;
    List<Judge> theJudgeList;
    boolean systemexitwhenclosed;
    Connection theDBConnection;
    LoadSQLiteConcoursDatabase  loadSQLiteConcoursDatabase;

    /**
     * Constructor
     * Creates new form CustomJudgeTeamDialog
     */
    public AddCustomJudgeTeamDialog(java.awt.Frame parent, boolean modal, Concours aConcours) {
        super(parent, modal);
        initComponents();
        
        systemexitwhenclosed = false;
        theConcours = aConcours;
        theDBConnection = aConcours.GetConnection();
        loadSQLiteConcoursDatabase = new LoadSQLiteConcoursDatabase();  // for function access only
        
        Statement stat = null;
        try {
            stat = theDBConnection.createStatement();
        } catch (SQLException ex) {
            okDialog("ERROR: SQL exception in AddCustomJudgeTeamDialog");
            theConcours.GetLogger().log(Level.SEVERE, "ERROR: SQL exception in AddCustomJudgeTeamDialog", ex);
            System.exit(-1);
        }

        cboClasses.setModel(new javax.swing.DefaultComboBoxModel(getClasses(theConcours).toArray()));
        cboClasses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClassesItemStateChanged(evt);
            }
        });
        theJudgeList = theConcours.GetConcoursJudges();
        judgeArray = theJudgeList.toArray(new Judge[theJudgeList.size()]);
        try {
            //q = "create table ConcoursClassPreassignedJudgesTable ('preassignedjudge_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'concoursclasses_id' INTEGER NOT NULL, 'judge_node' INTEGER NOT NULL, judge TEXT, FOREIGN KEY (concoursclasses_id) REFERENCES ConcoursClassesTable (concoursclasses_id));";
            stat.executeUpdate("create table if not exists ConcoursClassPreassignedJudgesTable ('preassignedjudge_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'concoursclasses_id' INTEGER NOT NULL, 'judge_node' INTEGER NOT NULL, judge TEXT, FOREIGN KEY (concoursclasses_id) REFERENCES ConcoursClassesTable (concoursclasses_id));");
        } catch (SQLException ex) {
            theConcours.GetLogger().log(Level.SEVERE, null, ex);
        }
        try {
            stat.close();
        } catch (SQLException ex) {
            theConcours.GetLogger().log(Level.SEVERE, null, ex);
        }
        
        PopulatePrefPanelCustomJudge(judgeArray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboClasses = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnFinished = new javax.swing.JButton();
        pnlPrefContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Judges allowed to judge a selected Class");

        cboClasses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboClasses.setToolTipText("Select a class for which you want to define a custom judging team.");
        cboClasses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClassesItemStateChanged(evt);
            }
        });
        cboClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClassesActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Concours class");

        btnAdd.setText("Add custom judging team");
        btnAdd.setToolTipText("Click after selecting the judges for the selected  class.");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFinished.setText("Finished");
        btnFinished.setToolTipText("Click after adding one or more custom judging teams");
        btnFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrefContentLayout = new javax.swing.GroupLayout(pnlPrefContent);
        pnlPrefContent.setLayout(pnlPrefContentLayout);
        pnlPrefContentLayout.setHorizontalGroup(
            pnlPrefContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        pnlPrefContentLayout.setVerticalGroup(
            pnlPrefContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrefContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnAdd)
                .addGap(26, 26, 26)
                .addComponent(btnFinished))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(58, 58, 58)
                .addComponent(pnlPrefContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnFinished))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClassesActionPerformed

    private void cboClassesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboClassesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClassesItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Add each selected Judge to the list of preassigned judges of the selected class 
        boolean ok = true;
        ConcoursClass cc = (ConcoursClass) cboClasses.getSelectedItem();
        int division = cc.GetClassDivision();
        ArrayList<String> pjl = CreatePreassignedJudgesList();  // list of checked boxes
        if(division == 1 && pjl.size() <2){
            okDialog("At least 2 Judges must be selected for Driven classes. Currently there are only " + pjl.size());
            ok = false;
        }
        if(division == 2 && pjl.size() < 3){
            okDialog("At least 3 Judges must be selected for Championship or Special classes. Currently there are only " + pjl.size());
            ok = false;
        }
        if(ok){
            String report = "The preassigned Judge list for Concours Class " + cc.GetClassName() + " has been set to:\n";
            for(String judgeUniqueName : pjl){
                Judge theJudge = theConcours.GetConcoursJudge(judgeUniqueName);
                cc.AddPreassignedJudge(theDBConnection, theJudge);
                report = report + theJudge.getUniqueName() + "\n";
            }
           // ++++++++++++
           // Changed 7/14/2016 to remove the no longer valid Judge Assignment/schedule tables from the database
           // the previouse Judge Assignment is now invalid so manual editing is disabled.
            // Also, might as well clear the JudgeAssignments Table and EntryJudgesTable
            theConcours.SetJudgeAssignmentCurrent(false); 
            try { 
                loadSQLiteConcoursDatabase.SetSettingsTableJAState(theDBConnection, false) ;
            } catch (SQLException ex) {
                //Logger.getLogger(AddCustomJudgeTeamDialog.class.getName()).log(Level.SEVERE, null, ex);
                String msg = "SQLException in AddCustomJudgeTeamDialog call to SetSettingsTableJAState";
                okDialog(msg);
                theConcours.GetLogger( ).log(Level.SEVERE, msg, ex);
            }
            // Trying again... 7/14/2016   WORKED.  No locked tables.
            theConcours.GetLogger().info("Calling ClearJudgeAssignmentsTables() in AddCustomJudgingTeam");
            // locked table again... 8/2/2017
            //loadSQLiteConcoursDatabase.ClearJudgeAssignmentsTables(theDBConnection);
           // ++++++++
            
            okDialog(report);
            theConcours.GetLogger().info(report);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishedActionPerformed
        boolean flag = theConcours.GetConcoursClassesObject().preassignedJudgeListsExists();
        theConcours.SetPreassignedJudgesFlag(flag);
        theConcours.SetJudgeAssignmentCurrent(false); 
        theConcours.GetLogger().info("Finished adding preassigned Judging team.");
        this.setVisible(false);
        this.dispose();
         // This is not wanted when the dialog is invoked by ConcourseGUI, but must be done when run by main()
         // or the process will continu to run!
        if(systemexitwhenclosed){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnFinishedActionPerformed

        private ArrayList<ConcoursClass> getClasses(Concours aConcours){
        return aConcours.GetConcoursClasses();
        
    }

    private void PopulatePrefPanelCustomJudge(Judge[] aJudgeArray)   {
        
        /* 
         * Iterate the list of Concours Judges to set up the checkbox list. 
         *  
         * All of this is set into a panel in the dialog
         */
        
        // Set up Judges panel

        pnlJudges = new javax.swing.JPanel();
        pnlJudges.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Judges allowed for the selected Class"));
        //
        //  Set up scrolling for the Judge panel
        //
        scrollPaneJudges = new JScrollPane(pnlJudges, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPaneJudges.setMinimumSize(null);
       
        javax.swing.BoxLayout pnlJudgesLayout;
        pnlJudgesLayout = new javax.swing.BoxLayout(pnlJudges, BoxLayout.PAGE_AXIS);
        pnlJudges.setLayout(pnlJudgesLayout);
        pnlJudges.revalidate();
        
        
        
        for (Judge j : aJudgeArray) {
            String uniqueName = j.getUniqueName();
            JCheckBox cb;
            cb = new JCheckBox(new Judge.JudgeAction(j));
            cb.setName(uniqueName);
            pnlJudges.add(cb);
        }
        pnlJudges.revalidate();
        pnlJudges.repaint();

        pnlPrefContent.setPreferredSize(new Dimension(300, 400));
       // pnlPrefContent.setPreferredSize(null);
        javax.swing.BoxLayout pnlPrefContentLayout;
        pnlPrefContentLayout = new javax.swing.BoxLayout(pnlPrefContent, BoxLayout.LINE_AXIS);
        pnlPrefContent.setLayout(pnlPrefContentLayout);
        pnlPrefContent.add(scrollPaneJudges);
        pnlPrefContent.setVisible(true);
    
    
}
    
    private ArrayList<String> CreatePreassignedJudgesList(){
        ArrayList<String> list = new ArrayList<>();
        Component [] components = pnlJudges.getComponents();
       for( Component c : components){
           JCheckBox cb = (JCheckBox) c;
           if(cb.isSelected() ){
               list.add(cb.getName() );
           }
       }
       return list;
    }    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomJudgeTeamDialog dialog = new CustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCustomJudgeTeamDialog dialog = new AddCustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
               */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFinished;
    private javax.swing.JComboBox cboClasses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPrefContent;
    // End of variables declaration//GEN-END:variables
}
