/* 
 * Copyright (C) 2017 Edward F Sowell
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package JCNAConcours;

import static JCNAConcours.AddConcoursEntryDialog.okDialog;
import static JCNAConcours.ConcoursGUI.theConcours;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import us.efsowell.concours.lib.Concours;
import us.efsowell.concours.lib.ConcoursClass;
//import us.efsowell.concours.lib.ConcoursPersonnel;
//import us.efsowell.concours.lib.JCNAClass;
import us.efsowell.concours.lib.Judge;
import us.efsowell.concours.lib.Judges;
import us.efsowell.concours.lib.LoadSQLiteConcoursDatabase;

/**
 *
 * @author Ed Sowell
 */
public class EditCustomJudgeTeamDialog extends javax.swing.JDialog {
    //JPanel pnlJCNAClassGroups;
   // JPanel pnlJudges;
   // JScrollPane scrollPaneJudges;
    
    Judge[] judgeArray;
    Concours theConcours;
    //ConcoursPersonnel theConcoursePersonnel;
    ArrayList<ConcoursClass> theClassesWithPreassignedJudges;
    
    Judges theConcoursJudges;
    List<Judge> theJudgeList;
    boolean systemexitwhenclosed;
    Connection theDBConnection;
    LoadSQLiteConcoursDatabase loadSQLiteConcoursDatabase;
    

    /**
     * Creates new form CustomJudgeTeamDialog
     */
    public EditCustomJudgeTeamDialog(java.awt.Frame parent, boolean modal, Concours aConcours) {
        super(parent, modal);
        initComponents();
        theConcours = aConcours;
        theDBConnection = aConcours.GetConnection();
        loadSQLiteConcoursDatabase = new LoadSQLiteConcoursDatabase();

        Statement stat = null;
        try {
            stat = theDBConnection.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        theClassesWithPreassignedJudges = getClassesWithPreassignedJudges(theConcours);
        cboClasses.setModel(new javax.swing.DefaultComboBoxModel(theClassesWithPreassignedJudges.toArray()));

        //cboClasses.setModel(new javax.swing.DefaultComboBoxModel(getClasses(theConcours).toArray()));
        cboClasses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClassesItemStateChanged(evt);
            }
        });
        theJudgeList = theConcours.GetConcoursJudges();
        judgeArray = theJudgeList.toArray(new Judge[theJudgeList.size()]);
        try {
            //q = "create table ConcoursClassPreassignedJudgesTable ('preassignedjudge_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'concoursclasses_id' INTEGER NOT NULL, 'judge_node' INTEGER NOT NULL, judge TEXT, FOREIGN KEY (concoursclasses_id) REFERENCES ConcoursClassesTable (concoursclasses_id));";
            stat.executeUpdate("create table if not exists ConcoursClassPreassignedJudgesTable ('preassignedjudge_id' INTEGER PRIMARY KEY AUTOINCREMENT, 'concoursclasses_id' INTEGER NOT NULL, 'judge_node' INTEGER NOT NULL, judge TEXT, FOREIGN KEY (concoursclasses_id) REFERENCES ConcoursClassesTable (concoursclasses_id));");
        } catch (SQLException ex) {
            Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stat.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Populate the Judge checkbox list with the first Concours class preassigns
        ConcoursClass cc = (ConcoursClass)cboClasses.getSelectedItem();
        PopulatePrefPanelEditCustomJudgingTeam(judgeArray, cc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        cboClasses = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnFinished = new javax.swing.JButton();
        spnlJudges1 = new javax.swing.JScrollPane();
        pnlJudges1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Judges allowed to judge a selected Class");

        cboClasses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboClasses.setToolTipText("Select the class for which the custom judging team is to be changed");
        cboClasses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClassesItemStateChanged(evt);
            }
        });
        cboClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClassesActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Concours class");

        btnFinished.setText("Finished");
        btnFinished.setToolTipText("Click after making wanted changes to one or more classes.");
        btnFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishedActionPerformed(evt);
            }
        });

        pnlJudges1.setLayout(new javax.swing.BoxLayout(pnlJudges1, javax.swing.BoxLayout.LINE_AXIS));
        spnlJudges1.setViewportView(pnlJudges1);

        btnSave.setText("Save");
        btnSave.setToolTipText("Click after selecting the team for the selected class. Can be used repeatedly.");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(spnlJudges1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinished)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(spnlJudges1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinished)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClassesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClassesActionPerformed

    private void cboClassesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboClassesItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
           ConcoursClass selectedconcoursclass = (ConcoursClass) cboClasses.getSelectedItem(); 
           Judge[] concoursJudgeArray = theJudgeList.toArray(new Judge[ selectedconcoursclass.GetClassPreassignedJudgeNameList().size()]);
           PopulatePrefPanelEditCustomJudgingTeam(concoursJudgeArray, selectedconcoursclass);
        }
    }//GEN-LAST:event_cboClassesItemStateChanged

    private ArrayList<ConcoursClass> getClassesWithPreassignedJudges(Concours aConcours){
        ArrayList<ConcoursClass> classesWithPreassignedJudges = new ArrayList<>();
        for(ConcoursClass cc : aConcours.GetConcoursClasses()){
            if(!cc.GetClassPreassignedJudgeNameList().isEmpty()){
                classesWithPreassignedJudges.add(cc);
            }
        }
        return classesWithPreassignedJudges;
    }
    
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishedActionPerformed
        theConcours.SetPreassignedJudgesFlag(theConcours.GetConcoursClassesObject().preassignedJudgeListsExists());
        theConcours.SetJudgeAssignmentCurrent(false); 
        theConcours.GetLogger().info("Finished Modifying Custom Judges");
        this.setVisible(false);
        this.dispose();
         // This is not wanted when the dialog is invoked by ConcourseGUI, but must be done when run by main()
         // or the process will continu to run!
        if(systemexitwhenclosed){
            System.exit(0);
        }
    }//GEN-LAST:event_btnFinishedActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Save the Judges panel selections to memory & database
        // Add each selected Judge to the list of preassigned judges of the selected class 
        boolean ok = true;
        ConcoursClass cc = (ConcoursClass) cboClasses.getSelectedItem();
        int division = cc.GetClassDivision();
        ArrayList<String> pjl = CreatePreassignedJudgesList();  // list of checked boxes
        if(division == 1 && pjl.size() <2){
            okDialog("At least 2 Judges must be selected for Driven classes. Currently there are only " + pjl.size());
            ok = false;
        }
        if(division == 2 && pjl.size() < 3){
            okDialog("At least 3 Judges must be selected for Championship or Special classes. Currently there are only " + pjl.size());
            ok = false;
        }
        if(ok){
            String report = "The preassigned Judge list for Concours Class " + cc.GetClassName() + " has been changed to:\n";
            cc.RemoveAllPreassignedJudges(theDBConnection); // Clear out
            for(String judgeUniqueName : pjl){
                Judge theJudge = theConcours.GetConcoursJudge(judgeUniqueName);
                cc.AddPreassignedJudge(theDBConnection, theJudge);
                report = report + theJudge.getUniqueName() + "\n";
            }
       // ++++++++++++
       // Changed 7/14/2016 to remove the no longer valid Judge Assignment/schedule tables from the database
       // the previouse Judge Assignment is now invalid so manual editing is disabled.
        // Also, might as well clear the JudgeAssignments Table and EntryJudgesTable
        theConcours.SetJudgeAssignmentCurrent(false); 
            try { 
                loadSQLiteConcoursDatabase.SetSettingsTableJAState(theDBConnection, false) ;
            } catch (SQLException ex) {
                String msg = "SQLException in EditCustomJudgingTeamDialog call to SetSettingsTableJAState";
                okDialog(msg);
                theConcours.GetLogger( ).log(Level.SEVERE, msg, ex);
            }
        // Trying again... 7/14/2016   WORKED.  No locked tables.
            // 8/1/2017 Getting locked tables in LoadSQLiteConcoursDatabase.JudgeAssignmentsMemToDB so once again disable this... unnecessary
        //theConcours.GetLogger().info("Calling ClearJudgeAssignmentsTables() in EditCustomJudgingTeamDialog");
        //loadSQLiteConcoursDatabase.ClearJudgeAssignmentsTables(theDBConnection);
       // ++++++++
            okDialog(report);
            theConcours.GetLogger().info(report);
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

        private ArrayList<ConcoursClass> getClasses(Concours aConcours){
        return aConcours.GetConcoursClasses();
        
    }

    private void PopulatePrefPanelEditCustomJudgingTeam(Judge[] aJudgeArray, ConcoursClass aSelectedConcoursClass)   {
        // Set up Judges panel
       // theConcours.GetLogger().info("Concours Class: " + aSelectedConcoursClass);

        pnlJudges1.removeAll();
        ArrayList<String> cpjl = aSelectedConcoursClass.GetClassPreassignedJudgeNameList();
        for (Judge j : aJudgeArray) {
            String uniqueName = j.getUniqueName();
            JCheckBox cb;
            cb = new JCheckBox(new Judge.JudgeAction(j));
            cb.setName(uniqueName);
            if(cpjl.contains(j.getUniqueName())){
                cb. setSelected(true);
            }
            pnlJudges1.add(cb);
        }
        //     
        //    These 2 lines are needed in order to display the checkbox list.  Apparently, the Layout Manager otherwise works with a different version of pneJudges
        //
        pnlJudges1.setLayout(new javax.swing.BoxLayout(pnlJudges1, javax.swing.BoxLayout.PAGE_AXIS));
        spnlJudges1.setViewportView(pnlJudges1);
        
        pnlJudges1.revalidate(); // Might not be needed ???
        pnlJudges1.repaint();
    
}
    
    private ArrayList<String> CreatePreassignedJudgesList(){
        ArrayList<String> list = new ArrayList<>();
        String report = "Preassigned judges" ;
        Component [] components = pnlJudges1.getComponents();
       for( Component c : components){
           JCheckBox cb = (JCheckBox) c;
           if(cb.isSelected() ){
               list.add(cb.getName() );
               report = report + " " + cb.getName();
           }
       }
       theConcours.GetLogger().info(report);
       return list;
    }    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomJudgeTeamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomJudgeTeamDialog dialog = new CustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomJudgeTeamDialog dialog = new CustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomJudgeTeamDialog dialog = new CustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        //</editor-fold>

        /* Create and display the dialog */
       /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomJudgeTeamDialog dialog = new CustomJudgeTeamDialog(new javax.swing.JFrame(), true);
               dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
               */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinished;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboClasses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlJudges1;
    private javax.swing.JScrollPane spnlJudges1;
    // End of variables declaration//GEN-END:variables
}
