/* 
 * Copyright (C) 2017 Edward F Sowell
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package editJA;

import static JCNAConcours.AddConcoursEntryDialog.okDialog;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import us.efsowell.concours.lib.Concours;
import us.efsowell.concours.lib.Entry;
import us.efsowell.concours.lib.TimeslotAssignment;

/**
 *
 * @author Ed Sowell
 */
public class ChangeEntryTSInputDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChangeEntryTSInputDialog
     */
   // private Integer theSelectedEntryNode;
  //  private Integer theSelectedNewTimeslotNode;
    Concours theConcours;
    
    Map<Integer,String> timeslotIndexToTimeStringMap; 
    Map<String, Integer> timeStringToTimeslotIndexMap; 

    public ChangeEntryTSInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    // Custom constructor to pass things to this dialog
    // 11/8/2018
//    public ChangeEntryTSInputDialog(java.awt.Frame parent, boolean modal, Concours aConcours, Map<Integer, String> aTimeslotIndexToTimeStringMap,  Map<String, Integer> aTimeStringToTimeslotIndexMap) {
    
    public ChangeEntryTSInputDialog(java.awt.Frame parent, boolean modal, Concours aConcours,  Map<Integer, String> aTimeslotIndexToTimeStringMap,  Map<String, Integer> aTimeStringToTimeslotIndexMap) {
        super(parent, modal);
        initComponents();
        // Populate the TimeslotAssignments array
        //ArrayList<TimeslotAssignment> timeslotAssignmentsRef = JudgeAssignGUI.getTimeslotAssignments();
        theConcours = aConcours;
        
        timeslotIndexToTimeStringMap = aTimeslotIndexToTimeStringMap;
        timeStringToTimeslotIndexMap = aTimeStringToTimeslotIndexMap;
        JudgeAssignDialog.theConcours.UpdateTimeslotStats();    // Before an changes.
        
        cboEntry.setModel(new javax.swing.DefaultComboBoxModel(getEntries(aConcours).toArray()));
        
        int numSlotsInUse = theConcours.getMaxTimeslotIndex() + 1;  // Before an changes.
        
        //Integer[] tsIndexAry = new Integer[numSlotsInUse +1 ]; 
        // the +1 will allow user to move an entry into a new timeslot at end
        String[] tsTextAry = new String[numSlotsInUse +1 ]; 
        for(int i=0; i<numSlotsInUse + 1; i++ ){
           tsTextAry[i] = aTimeslotIndexToTimeStringMap.get(i);
        }
        
        
        //cboTimeslot.setModel(new javax.swing.DefaultComboBoxModel(getTimeslots().toArray()));
       cboTimeslot.setModel(new javax.swing.DefaultComboBoxModel(tsTextAry));
   }

    
    
    
    private List<String> getEntryStrings(Concours theConcours){
        return JudgeAssignDialog.theConcours.GetEntriesIDs();
    }
    private int getEntryNode(Concours theConcours, int i){
        return JudgeAssignDialog.theConcours.GetEntriesList().get(i).GetNode();
    }
    private List<Entry> getEntries(Concours theConcours){
        return JudgeAssignDialog.theConcours.GetEntriesList();
        
    }
    private static List<TimeslotAssignment> getTimeslots(){
       return (ArrayList<TimeslotAssignment>) JudgeAssignGUI.theConcours.GetTimeslotAssignments();
        
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        cboTimeslot = new javax.swing.JComboBox();
        OkButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        cboEntry = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboTimeslot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        cboEntry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEntry.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEntryItemStateChanged(evt);
            }
        });
        cboEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEntryActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Entry");

        jLabel2.setText("Select Timeslot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboTimeslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(OkButton)
                        .addGap(1, 1, 1)
                        .addComponent(CancelButton)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTimeslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkButton)
                    .addComponent(CancelButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
       // theConcours.GetLogger().info("Timeslot OkButtonActionPerformed() started");
        String res = "";
        Integer theEntryNode;
        String theNewTimeslotString;
        Integer theNewTimeslotIndex;
        Entry theSelectedEntry;
        theSelectedEntry = (Entry)cboEntry.getSelectedItem();
        theConcours.GetLogger().info("Timeslot OkButtonActionPerformed() started for Entry " + theSelectedEntry.GetUniqueDescription());
        theEntryNode =  theSelectedEntry.getValue();
        theNewTimeslotString = (String)cboTimeslot.getSelectedItem();
        
        theNewTimeslotIndex = timeStringToTimeslotIndexMap.get(theNewTimeslotString);
        
        res = JudgeAssignGUI.theConcours.changeEntryTimeslot(JudgeAssignGUI.theConcours.GetTimeslotAssignments(),  theEntryNode, theNewTimeslotIndex, timeslotIndexToTimeStringMap); 
        okDialog("\nTimeslot change: " + res + "\n");
        theConcours.GetLogger().info("Timeslot change result: " + res);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    private void cboEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEntryActionPerformed
        
    }//GEN-LAST:event_cboEntryActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void cboEntryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEntryItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEntryItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeEntryTSInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeEntryTSInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeEntryTSInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeEntryTSInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeEntryTSInputDialog dialog = new ChangeEntryTSInputDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton OkButton;
    private javax.swing.JComboBox cboEntry;
    private javax.swing.JComboBox cboTimeslot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
